export interface DemoAgent {
  id: string;
  name: string;
  initials: string;
  role: 'owner' | 'manager' | 'agent';
  ap_30d: number;
  deals_30d: number;
  deals_won: number;
  calls_30d: number;
  win_rate: number;
  last_active: string;
  status: 'active' | 'silent' | 'at_risk';
  coaching_note?: string;
}

export interface DemoClient {
  id: string;
  name: string;
  phone: string;
  email: string;
  agent_id: string;
  agent: string;
  stage: string;
  source: string;
  ap: number;
  ai_score: number;
  follow_up: string;
  received: string;
}

export interface DemoDeal {
  id: string;
  agent_id: string;
  agent: string;
  agent_initials: string;
  client: string;
  carrier: string;
  product: string;
  ap: number;
  commission: number;
  status: 'Issued' | 'Approved' | 'Underwriting' | 'Pending' | 'Submitted' | 'Declined';
  policy_number: string | null;
  submitted: string;
  draft_date: string | null;
  deposits: number;
  outstanding: number;
  ai_close_prob: number;
  ai_next_action: string;
}

export const AGENTS = [
  'Isaiah Auman',
  'Evan Scott',
  'Shea Scott',
  'Jason Rittman',
  'Nick Paolella',
];

export const DEMO_AGENTS: DemoAgent[] = [
  {
    id: 'a1',
    name: 'Isaiah Auman',
    initials: 'IA',
    role: 'agent',
    ap_30d: 92400,
    deals_30d: 12,
    deals_won: 8,
    calls_30d: 47,
    win_rate: 0.67,
    last_active: '2h ago',
    status: 'active',
  },
  {
    id: 'a2',
    name: 'Evan Scott',
    initials: 'ES',
    role: 'agent',
    ap_30d: 67200,
    deals_30d: 9,
    deals_won: 5,
    calls_30d: 38,
    win_rate: 0.56,
    last_active: '4h ago',
    status: 'active',
  },
  {
    id: 'a3',
    name: 'Shea Scott',
    initials: 'SS',
    role: 'agent',
    ap_30d: 48000,
    deals_30d: 7,
    deals_won: 4,
    calls_30d: 12,
    win_rate: 0.57,
    last_active: '48h ago',
    status: 'silent',
    coaching_note:
      '2 deals in underwriting, no activity logged in 2 days. Risk of going cold.',
  },
  {
    id: 'a4',
    name: 'Jason Rittman',
    initials: 'JR',
    role: 'manager',
    ap_30d: 34800,
    deals_30d: 5,
    deals_won: 3,
    calls_30d: 29,
    win_rate: 0.6,
    last_active: '1h ago',
    status: 'active',
  },
  {
    id: 'a5',
    name: 'Nick Paolella',
    initials: 'NP',
    role: 'agent',
    ap_30d: 12000,
    deals_30d: 2,
    deals_won: 1,
    calls_30d: 18,
    win_rate: 0.5,
    last_active: '3h ago',
    status: 'at_risk',
    coaching_note:
      'Conversion 31% vs team avg 58%. Needs call review and objection coaching.',
  },
];

export const DEMO_CLIENTS: DemoClient[] = [
  {
    id: 'c1',
    name: 'Kenji Yamamoto',
    phone: '(615) 882-4401',
    email: 'kenji.yamamoto@gmail.com',
    agent_id: 'a1',
    agent: 'Isaiah Auman',
    stage: 'policy_delivered',
    source: 'Live Transfer',
    ap: 4800,
    ai_score: 82,
    follow_up: '2026-04-29',
    received: '2026-04-10',
  },
  {
    id: 'c2',
    name: 'Leila Saadi',
    phone: '(704) 553-9210',
    email: 'leila.saadi@outlook.com',
    agent_id: 'a1',
    agent: 'Isaiah Auman',
    stage: 'new',
    source: 'Referral',
    ap: 2400,
    ai_score: 91,
    follow_up: '2026-04-28',
    received: '2026-04-21',
  },
  {
    id: 'c3',
    name: 'Roy Tillman',
    phone: '(843) 774-2290',
    email: 'rtillman55@yahoo.com',
    agent_id: 'a1',
    agent: 'Isaiah Auman',
    stage: 'underwriting',
    source: 'Aged FEX Lead',
    ap: 840,
    ai_score: 74,
    follow_up: '2026-04-30',
    received: '2026-04-15',
  },
  {
    id: 'c4',
    name: 'Debra Fontaine',
    phone: '(504) 661-3388',
    email: 'dfontaine@bellsouth.net',
    agent_id: 'a2',
    agent: 'Evan Scott',
    stage: 'approved',
    source: 'Direct Mail',
    ap: 1920,
    ai_score: 88,
    follow_up: '2026-04-29',
    received: '2026-04-08',
  },
  {
    id: 'c5',
    name: 'Marcus Webb',
    phone: '(919) 340-7712',
    email: 'marcus.webb@gmail.com',
    agent_id: 'a2',
    agent: 'Evan Scott',
    stage: 'new',
    source: 'Referral',
    ap: 3600,
    ai_score: 79,
    follow_up: '2026-04-28',
    received: '2026-04-22',
  },
  {
    id: 'c6',
    name: 'Sandra Cho',
    phone: '(312) 492-0034',
    email: 'sandracho.ins@gmail.com',
    agent_id: 'a2',
    agent: 'Evan Scott',
    stage: 'underwriting',
    source: 'Web Form',
    ap: 2160,
    ai_score: 65,
    follow_up: '2026-05-01',
    received: '2026-04-17',
  },
  {
    id: 'c7',
    name: 'Tony Breckenridge',
    phone: '(770) 884-5521',
    email: 'tbreckenridge@hotmail.com',
    agent_id: 'a3',
    agent: 'Shea Scott',
    stage: 'underwriting',
    source: 'Aged FEX Lead',
    ap: 1440,
    ai_score: 58,
    follow_up: '2026-04-28',
    received: '2026-04-14',
  },
  {
    id: 'c8',
    name: 'Gloria Perkins',
    phone: '(901) 773-2291',
    email: 'gloria.perkins@yahoo.com',
    agent_id: 'a3',
    agent: 'Shea Scott',
    stage: 'underwriting',
    source: 'Direct Mail',
    ap: 1080,
    ai_score: 61,
    follow_up: '2026-04-30',
    received: '2026-04-16',
  },
  {
    id: 'c9',
    name: 'Harold Simms',
    phone: '(251) 449-6610',
    email: 'hsimms@charter.net',
    agent_id: 'a3',
    agent: 'Shea Scott',
    stage: 'new',
    source: 'Aged FEX Lead',
    ap: 960,
    ai_score: 47,
    follow_up: '2026-05-02',
    received: '2026-04-23',
  },
  {
    id: 'c10',
    name: 'Angela Reyes',
    phone: '(210) 554-8823',
    email: 'angela.reyes@gmail.com',
    agent_id: 'a4',
    agent: 'Jason Rittman',
    stage: 'approved',
    source: 'Live Transfer',
    ap: 2880,
    ai_score: 85,
    follow_up: '2026-04-29',
    received: '2026-04-11',
  },
  {
    id: 'c11',
    name: 'Curtis Holman',
    phone: '(404) 229-7745',
    email: 'cholman.ins@outlook.com',
    agent_id: 'a4',
    agent: 'Jason Rittman',
    stage: 'policy_delivered',
    source: 'Referral',
    ap: 3240,
    ai_score: 93,
    follow_up: '2026-05-05',
    received: '2026-04-07',
  },
  {
    id: 'c12',
    name: 'Brenda Kowalski',
    phone: '(414) 882-3310',
    email: 'bkowalski55@gmail.com',
    agent_id: 'a5',
    agent: 'Nick Paolella',
    stage: 'new',
    source: 'Web Form',
    ap: 1200,
    ai_score: 52,
    follow_up: '2026-04-28',
    received: '2026-04-20',
  },
  {
    id: 'c13',
    name: 'Terrence Bullock',
    phone: '(615) 330-9987',
    email: 'tbullock@yahoo.com',
    agent_id: 'a5',
    agent: 'Nick Paolella',
    stage: 'lapsed',
    source: 'Aged FEX Lead',
    ap: 720,
    ai_score: 45,
    follow_up: '2026-05-03',
    received: '2026-04-03',
  },
  {
    id: 'c14',
    name: 'Patricia Osei',
    phone: '(678) 441-2209',
    email: 'patriciaosei@gmail.com',
    agent_id: 'a1',
    agent: 'Isaiah Auman',
    stage: 'approved',
    source: 'Referral',
    ap: 3600,
    ai_score: 89,
    follow_up: '2026-04-30',
    received: '2026-04-12',
  },
  {
    id: 'c15',
    name: 'Vincent Caruso',
    phone: '(305) 772-5543',
    email: 'vcaruso@comcast.net',
    agent_id: 'a2',
    agent: 'Evan Scott',
    stage: 'policy_delivered',
    source: 'Live Transfer',
    ap: 2640,
    ai_score: 77,
    follow_up: '2026-05-06',
    received: '2026-04-06',
  },
];

export const DEMO_DEALS: DemoDeal[] = [
  {
    id: 'd1',
    agent_id: 'a1',
    agent: 'Isaiah Auman',
    agent_initials: 'IA',
    client: 'Kenji Yamamoto',
    carrier: 'F&G',
    product: 'Whole Life',
    ap: 4800,
    commission: Math.round(4800 * 0.75),
    status: 'Issued',
    policy_number: 'FG-2026-114892',
    submitted: '2026-04-12',
    draft_date: '2026-05-01',
    deposits: 400,
    outstanding: 0,
    ai_close_prob: 97,
    ai_next_action: 'Policy issued — schedule delivery call and referral ask.',
  },
  {
    id: 'd2',
    agent_id: 'a1',
    agent: 'Isaiah Auman',
    agent_initials: 'IA',
    client: 'Patricia Osei',
    carrier: 'Transamerica',
    product: 'Final Expense',
    ap: 3600,
    commission: Math.round(3600 * 0.85),
    status: 'Approved',
    policy_number: 'TA-2026-228471',
    submitted: '2026-04-15',
    draft_date: '2026-05-01',
    deposits: 300,
    outstanding: 0,
    ai_close_prob: 94,
    ai_next_action: 'Approved — confirm draft date and send welcome email.',
  },
  {
    id: 'd3',
    agent_id: 'a1',
    agent: 'Isaiah Auman',
    agent_initials: 'IA',
    client: 'Leila Saadi',
    carrier: 'Mutual of Omaha',
    product: 'Final Expense',
    ap: 2400,
    commission: Math.round(2400 * 0.85),
    status: 'Underwriting',
    policy_number: null,
    submitted: '2026-04-20',
    draft_date: null,
    deposits: 0,
    outstanding: 2400,
    ai_close_prob: 78,
    ai_next_action: 'Call carrier for underwriting status — day 8, check for missing APS.',
  },
  {
    id: 'd4',
    agent_id: 'a2',
    agent: 'Evan Scott',
    agent_initials: 'ES',
    client: 'Debra Fontaine',
    carrier: 'ETHOS',
    product: 'Term',
    ap: 1920,
    commission: Math.round(1920 * 0.55),
    status: 'Issued',
    policy_number: 'ET-2026-003318',
    submitted: '2026-04-11',
    draft_date: '2026-05-01',
    deposits: 160,
    outstanding: 0,
    ai_close_prob: 98,
    ai_next_action: 'Issued — ask for 2 referrals at delivery.',
  },
  {
    id: 'd5',
    agent_id: 'a2',
    agent: 'Evan Scott',
    agent_initials: 'ES',
    client: 'Vincent Caruso',
    carrier: 'Foresters',
    product: 'Whole Life',
    ap: 2640,
    commission: Math.round(2640 * 0.75),
    status: 'Issued',
    policy_number: 'FOR-2026-099241',
    submitted: '2026-04-09',
    draft_date: '2026-04-20',
    deposits: 220,
    outstanding: 0,
    ai_close_prob: 97,
    ai_next_action: 'Policy active — review for cross-sell opportunity next quarter.',
  },
  {
    id: 'd6',
    agent_id: 'a3',
    agent: 'Shea Scott',
    agent_initials: 'SS',
    client: 'Tony Breckenridge',
    carrier: 'Transamerica',
    product: 'Final Expense',
    ap: 1440,
    commission: Math.round(1440 * 0.85),
    status: 'Underwriting',
    policy_number: null,
    submitted: '2026-04-18',
    draft_date: null,
    deposits: 0,
    outstanding: 1440,
    ai_close_prob: 61,
    ai_next_action: 'No agent contact in 48h — call carrier and update client today.',
  },
  {
    id: 'd7',
    agent_id: 'a3',
    agent: 'Shea Scott',
    agent_initials: 'SS',
    client: 'Gloria Perkins',
    carrier: 'Mutual of Omaha',
    product: 'Final Expense',
    ap: 1080,
    commission: Math.round(1080 * 0.85),
    status: 'Underwriting',
    policy_number: null,
    submitted: '2026-04-19',
    draft_date: null,
    deposits: 0,
    outstanding: 1080,
    ai_close_prob: 58,
    ai_next_action: 'At risk — follow up with carrier and client before end of week.',
  },
  {
    id: 'd8',
    agent_id: 'a4',
    agent: 'Jason Rittman',
    agent_initials: 'JR',
    client: 'Angela Reyes',
    carrier: 'F&G',
    product: 'IUL',
    ap: 4200,
    commission: Math.round(4200 * 0.75),
    status: 'Approved',
    policy_number: 'FG-2026-118834',
    submitted: '2026-04-14',
    draft_date: '2026-05-05',
    deposits: 350,
    outstanding: 0,
    ai_close_prob: 91,
    ai_next_action: 'Approved — confirm draft and schedule IUL illustration review.',
  },
  {
    id: 'd9',
    agent_id: 'a5',
    agent: 'Nick Paolella',
    agent_initials: 'NP',
    client: 'Brenda Kowalski',
    carrier: 'ETHOS',
    product: 'Term',
    ap: 1200,
    commission: Math.round(1200 * 0.55),
    status: 'Pending',
    policy_number: null,
    submitted: '2026-04-22',
    draft_date: null,
    deposits: 0,
    outstanding: 1200,
    ai_close_prob: 54,
    ai_next_action: 'Pending 6 days — verify application is complete and resubmit if needed.',
  },
  {
    id: 'd10',
    agent_id: 'a4',
    agent: 'Jason Rittman',
    agent_initials: 'JR',
    client: 'Curtis Holman',
    carrier: 'Foresters',
    product: 'Whole Life',
    ap: 3240,
    commission: Math.round(3240 * 0.75),
    status: 'Submitted',
    policy_number: null,
    submitted: '2026-04-25',
    draft_date: null,
    deposits: 0,
    outstanding: 3240,
    ai_close_prob: 83,
    ai_next_action: 'Submitted yesterday — confirm receipt with carrier and set 5-day follow-up.',
  },
];

// MOCK_PIPELINE — array format expected by leads/page.tsx
export const MOCK_PIPELINE = [
  { id: 'p1', name: 'Cassandra Reeves', source: 'Aged FEX Lead', stage: 'New', agent: 'Isaiah Auman', attempts: 0, est_ap_cents: 120000, last_touch: '2026-04-27' },
  { id: 'p2', name: 'Henry Okafor', source: 'Live Transfer', stage: 'Contacted', agent: 'Evan Scott', attempts: 2, est_ap_cents: 96000, last_touch: '2026-04-26' },
  { id: 'p3', name: 'Leila Saadi', source: 'Referral', stage: 'Qualified', agent: 'Isaiah Auman', attempts: 3, est_ap_cents: 240000, last_touch: '2026-04-26' },
  { id: 'p4', name: 'Roy Tillman', source: 'Aged FEX Lead', stage: 'Quoted', agent: 'Nick Paolella', attempts: 4, est_ap_cents: 84000, last_touch: '2026-04-25' },
  { id: 'p5', name: 'Imani Brooks', source: 'Live Transfer', stage: 'App Started', agent: 'Shea Scott', attempts: 5, est_ap_cents: 144000, last_touch: '2026-04-25' },
  { id: 'p6', name: 'Marcus Wenz', source: 'Referral', stage: 'Submitted', agent: 'Evan Scott', attempts: 6, est_ap_cents: 312000, last_touch: '2026-04-24' },
  { id: 'p7', name: 'Olusegun Adeyemi', source: 'Aged FEX Lead', stage: 'Contacted', agent: 'Jason Rittman', attempts: 1, est_ap_cents: 108000, last_touch: '2026-04-27' },
  { id: 'p8', name: 'Annika Sjoberg', source: 'Web Form', stage: 'New', agent: '—', attempts: 0, est_ap_cents: 180000, last_touch: '2026-04-27' },
  { id: 'p9', name: 'Devontae Marsh', source: 'Aged FEX Lead', stage: 'Quoted', agent: 'Nick Paolella', attempts: 4, est_ap_cents: 72000, last_touch: '2026-04-26' },
  { id: 'p10', name: 'Priya Venkatesh', source: 'Referral', stage: 'App Started', agent: 'Shea Scott', attempts: 3, est_ap_cents: 360000, last_touch: '2026-04-25' },
];

export const MOCK_RECRUITING = [
  { id: 'r1', name: 'Andre Whitlock', stage: 'Invited', source: 'Indeed', state: 'TX', recruiter: 'Isaiah Auman', invited_at: '2026-04-26', next_step: 'Send onboarding link' },
  { id: 'r2', name: 'Brittany Holcomb', stage: 'Onboarding', source: 'Referral', state: 'FL', recruiter: 'Jason Rittman', invited_at: '2026-04-24', next_step: 'Complete e-sign contract' },
  { id: 'r3', name: 'Caleb Donatello', stage: 'Contracted', source: 'LinkedIn', state: 'GA', recruiter: 'Evan Scott', invited_at: '2026-04-21', next_step: 'Submit license/NPN' },
  { id: 'r4', name: 'Daniela Ferrer', stage: 'Licensed', source: 'Referral', state: 'TX', recruiter: 'Isaiah Auman', invited_at: '2026-04-18', next_step: 'Carrier appointment: Transamerica' },
  { id: 'r5', name: 'Ethan Wakefield', stage: 'Appointed', source: 'Indeed', state: 'OH', recruiter: 'Jason Rittman', invited_at: '2026-04-15', next_step: 'First call shadow' },
];

// MOCK_LEAD_VENDORS — field shapes expected by leads/page.tsx
export const MOCK_LEAD_VENDORS = [
  { id: 'lv1', name: 'Aged FEX 181+ Days', type: 'Aged', cost_per_lead_cents: 75, leads_30d: 412, closed_30d: 38, ap_30d_cents: 4200000, active: true },
  { id: 'lv2', name: 'Life Jacket Vet', type: 'Live Transfer', cost_per_lead_cents: 4500, leads_30d: 88, closed_30d: 19, ap_30d_cents: 2880000, active: true },
  { id: 'lv3', name: 'Referral', type: 'Referral', cost_per_lead_cents: 0, leads_30d: 31, closed_30d: 14, ap_30d_cents: 3360000, active: true },
  { id: 'lv4', name: 'Direct Mail – FEX Q2', type: 'Direct Mail', cost_per_lead_cents: 8200, leads_30d: 22, closed_30d: 6, ap_30d_cents: 540000, active: true },
  { id: 'lv5', name: 'KOINO Web Form', type: 'Web Form', cost_per_lead_cents: 0, leads_30d: 17, closed_30d: 3, ap_30d_cents: 384000, active: true },
  { id: 'lv6', name: 'FB Lead Ad — Final Expense', type: 'Web Form', cost_per_lead_cents: 1850, leads_30d: 64, closed_30d: 8, ap_30d_cents: 720000, active: false },
];
