import StubPage from "@/components/StubPage";
export default function Page() {
  return <StubPage title="Follow-ups" subtitle="Scheduled tasks tied to leads and clients — auto-generated by AI." />;
}
