-- 0041_close_schema_drift.sql
--
-- ⚠️  NOT EXECUTABLE — kept as documentation of expected schema.
--
-- Original intent: backfill `if not exists` table definitions for tables
-- referenced in code but not present in this branch's local 00NN_* migration
-- chain (agencies, agency_members, agency_invites, agency_notifications,
-- agency_audit_log, routing_rules, etc.).
--
-- Status on production (jfphwmzwteermalzwojp) as of 2026-05-16: all the
-- target tables ALREADY EXIST, installed via the deployed DB's parallel
-- timestamp-format migration tracker. Running the original DDL would be
-- a no-op (all statements were `if not exists`) but it adds churn to the
-- migration tracker without clarity. See `audits/MIGRATION_APPLY_2026-05-16.md`.
--
-- Source-of-truth for what's actually in the deployed schema: query
-- `information_schema.columns` via the Supabase MCP. The intent of this
-- file lives in `audits/SCHEMA_DRIFT.md`.
--
-- If running against a fresh DB clone: revive this file from git history.

select 1 where false;  -- no-op placeholder
